  export const filterData = [
    {
      "id": 1,
      "title": "Loyal Labrador",
      "name": "Buddy",
      "breed": "Labrador Retriever",
      "type": "Dog",
      "location": "New York, NY",
      "specifications": ["Friendly", "Loyal", "Good with kids"],
      "briefDetail": "Buddy is a loving Labrador who enjoys outdoor activities and is great with children.",
      "detailedDetails": "Buddy is 4 years old, fully vaccinated, and has a calm demeanor. He loves playing fetch and is well-trained.",
      "imgUrl": "https://yt3.googleusercontent.com/ytc/AIdro_lu582LcG0w_tda0Ui4E08ZJyQnRnUXcxCPV8h05Pm2uA=s900-c-k-c0x00ffffff-no-rj"
    },
    {
      "id": 2,
      "title": "Curious Calico",
      "name": "Whiskers",
      "breed": "Calico",
      "type": "Cat",
      "location": "Los Angeles, CA",
      "specifications": ["Independent", "Playful", "Curious"],
      "briefDetail": "Whiskers is an independent Calico cat who loves to explore and play with toys.",
      "detailedDetails": "Whiskers is 2 years old, spayed, and enjoys lounging in the sun. She has a playful nature and loves chasing laser pointers.",
      "imgUrl": "https://as1.ftcdn.net/v2/jpg/03/60/79/46/1000_F_360794641_xzRpOR1Lw7vga9MFodSy8undko0aErf2.jpg"
    },
    {
      "id": 3,
      "title": "Chirpy Cockatiel",
      "name": "Sunny",
      "breed": "Cockatiel",
      "type": "Bird",
      "location": "Chicago, IL",
      "specifications": ["Social", "Mimics sounds", "Low maintenance"],
      "briefDetail": "Sunny is a cheerful Cockatiel who loves to chirp and interact with people.",
      "detailedDetails": "Sunny is 1 year old and enjoys whistling tunes. She is easy to care for and can mimic various sounds.",
      "imgUrl": "https://img.freepik.com/premium-photo/chirpy-cockatiel-bird-colorful-exotic-pet-generate-ai_98402-82943.jpg"
    },
    {
      "id": 4,
      "title": "Gentle Giant",
      "name": "Max",
      "breed": "Great Dane",
      "type": "Dog",
      "location": "Houston, TX",
      "specifications": ["Gentle", "Loyal", "Good with kids"],
      "briefDetail": "Max is a gentle Great Dane who loves to cuddle and is great with children.",
      "detailedDetails": "Max is 5 years old, neutered, and loves to lounge around the house. Despite his size, he is very gentle and affectionate.",
      "imgUrl": "https://cdn-images.vetstreet.com/88/98/c717c9154f2b8b8935ee3f651f94/saint-bernard-ap-1fjqfu-590.jpg"
    },
    {
      "id": 5,
      "title": "Playful Persian",
      "name": "Bella",
      "breed": "Persian",
      "type": "Cat",
      "location": "Phoenix, AZ",
      "specifications": ["Calm", "Affectionate", "Low maintenance"],
      "briefDetail": "Bella is a calm and affectionate Persian cat who enjoys quiet time and gentle petting.",
      "detailedDetails": "Bella is 3 years old, spayed, and has a luxurious coat that requires regular grooming. She is very affectionate and enjoys lounging in cozy spots.",
      "imgUrl": "https://i.pinimg.com/474x/f0/44/a4/f044a4c840223799f2b9217ecf67b3cc.jpg"
    },
    {
      "id": 6,
      "title": "Vibrant Parakeet",
      "name": "Blue",
      "breed": "Parakeet",
      "type": "Bird",
      "location": "Philadelphia, PA",
      "specifications": ["Colorful", "Social", "Loves to sing"],
      "briefDetail": "Blue is a vibrant Parakeet who loves to sing and interact with people.",
      "detailedDetails": "Blue is 6 months old and enjoys chirping along with music. He is social and enjoys being around people.",
      "imgUrl": "https://www.shutterstock.com/image-photo/beautiful-bright-parrot-on-white-600nw-2481626187.jpg"
    },
    {
      "id": 7,
      "title": "Energetic Beagle",
      "name": "Charlie",
      "breed": "Beagle",
      "type": "Dog",
      "location": "San Antonio, TX",
      "specifications": ["Energetic", "Curious", "Loves to explore"],
      "briefDetail": "Charlie is an energetic Beagle who loves to explore new places and follow scents.",
      "detailedDetails": "Charlie is 2 years old, neutered, and has a lot of energy. He loves going for long walks and exploring new areas.",
      "imgUrl": "https://t3.ftcdn.net/jpg/07/68/95/36/360_F_768953663_eY92U0PRImGGGAXn4vejvvYyouqnlE3q.jpg"
    },
    {
      "id": 8,
      "title": "Elegant Siamese",
      "name": "Luna",
      "breed": "Siamese",
      "type": "Cat",
      "location": "San Diego, CA",
      "specifications": ["Vocal", "Affectionate", "Intelligent"],
      "briefDetail": "Luna is an elegant Siamese cat who loves attention and is very vocal.",
      "detailedDetails": "Luna is 4 years old, spayed, and has a sleek, elegant appearance. She is very intelligent and enjoys interactive toys.",
      "imgUrl": "https://pikwizard.com/pw/medium/4bc8951a88ef644951c093c9f180d247.jpg"
    },
    {
      "id": 9,
      "title": "Friendly Golden",
      "name": "Daisy",
      "breed": "Golden Retriever",
      "type": "Dog",
      "location": "Dallas, TX",
      "specifications": ["Friendly", "Loyal", "Good with kids"],
      "briefDetail": "Daisy is a friendly Golden Retriever who loves to play and is great with children.",
      "detailedDetails": "Daisy is 3 years old, fully vaccinated, and has a loving personality. She enjoys playing fetch and spending time with her family.",
      "imgUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTeTN2tVoiIIm34ynD2vKXqtJf2sC0tnryQXw&s"
    },
    {
      "id": 10,
      "title": "Charming Canary",
      "name": "Goldie",
      "breed": "Canary",
      "type": "Bird",
      "location": "San Jose, CA",
      "specifications": ["Melodious", "Bright", "Easy to care for"],
      "briefDetail": "Goldie is a charming Canary with a beautiful singing voice.",
      "detailedDetails": "Goldie is 1 year old and loves to sing throughout the day. She is bright yellow and easy to care for.",
      "imgUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTWfAOxkfpECOeM5RqLD2ACr17U0GvgSz_ahQ&s"
    },
    {
      "id": 11,
      "title": "Brave Boxer",
      "name": "Rocky",
      "breed": "Boxer",
      "type": "Dog",
      "location": "Austin, TX",
      "specifications": ["Brave", "Loyal", "Energetic"],
      "briefDetail": "Rocky is a brave and loyal Boxer who enjoys outdoor activities and is very protective.",
      "detailedDetails": "Rocky is 4 years old, neutered, and has a muscular build. He is very energetic and loves to run and play.",
      "imgUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRHxyCtPHhogqf6pl_vMfT0ODIUy_KVauQgOw&s"
    },
    {
      "id": 12,
      "title": "Mischievous Maine Coon",
      "name": "Oliver",
      "breed": "Maine Coon",
      "type": "Cat",
      "location": "Jacksonville, FL",
      "specifications": ["Playful", "Affectionate", "Large breed"],
      "briefDetail": "Oliver is a mischievous Maine Coon who loves to play and is very affectionate.",
      "detailedDetails": "Oliver is 3 years old, neutered, and has a large, fluffy coat. He is very playful and enjoys interacting with his owners.",
      "imgUrl": "https://as1.ftcdn.net/v2/jpg/06/24/10/98/1000_F_624109875_a5AoKck0LE9CKuD97Y5GC5uwPcX5CYHz.jpg"
    },
    {
      "id": 13,
      "title": "Colorful Conure",
      "name": "Tiki",
      "breed": "Conure",
      "type": "Bird",
      "location": "Fort Worth, TX",
      "specifications": ["Colorful", "Social", "Loves attention"],
      "briefDetail": "Tiki is a colorful Conure who loves to interact with people and show off his vibrant feathers.",
      "detailedDetails": "Tiki is 2 years old and enjoys being the center of attention. He is very social and loves to show off his tricks.",
      "imgUrl": "https://media.istockphoto.com/id/159449929/photo/love-birds.jpg?s=612x612&w=0&k=20&c=D_gkSXepfp-DLKqRxID9a0gwbRlXtmseSyUx386B7Vw="
    },
    {
      "id": 14,
      "title": "Cuddly Cocker Spaniel",
      "name": "Molly",
      "breed": "Cocker Spaniel",
      "type": "Dog",
      "location": "Charlotte, NC",
      "specifications": ["Cuddly", "Friendly", "Good with kids"],
      "briefDetail": "Molly is a cuddly Cocker Spaniel who loves to be around people and is great with children.",
      "detailedDetails": "Molly is 5 years old, spayed, and loves to cuddle. She enjoys playing with toys and is very affectionate.",
      "imgUrl": "https://media.istockphoto.com/id/1341818129/photo/cute-and-sweet-cocker-spaniel-dog-with-tongue-sticking-out-sitting-isolated-over-white.jpg?s=612x612&w=0&k=20&c=rzmP7ttYUTxqOASihtB4P0r2_mhf365NawPVtwuItow="
    },
    {
      "id": 15,
      "title": "Gentle Rabbit",
      "name": "Flopsy",
      "breed": "Holland Lop",
      "type": "Rabbit",
      "location": "Indianapolis, IN",
      "specifications": ["Gentle", "Low maintenance", "Loves to hop"],
      "briefDetail": "Flopsy is a gentle Holland Lop rabbit who enjoys hopping around and is easy to care for.",
      "detailedDetails": "Flopsy is 1 year old and loves to play with toys and explore. She is gentle and low maintenance, making her a great pet for families.",
      "imgUrl": "https://cdn-fastly.petguide.com/media/2022/04/07/8297058/10-most-affectionate-rabbit-breeds.jpg?size=720x845&nocrop=1"
    },
    {
      "id": 16,
      "title": "Sociable Budgie",
      "name": "Sky",
      "breed": "Budgerigar",
      "type": "Bird",
      "location": "Columbus, OH",
      "specifications": ["Sociable", "Vocal", "Easy to train"],
      "briefDetail": "Sky is a sociable Budgie who loves to interact with people and is easy to train.",
      "detailedDetails": "Sky is 6 months old and enjoys learning new tricks. He is very vocal and loves to be the center of attention.",
      "imgUrl": "https://www.animalfunfacts.net/images/stories/pets/birds/budgies_l.jpg"
    },
    {
      "id": 17,
      "title": "Adventurous Chihuahua",
      "name": "Coco",
      "breed": "Chihuahua",
      "type": "Dog",
      "location": "San Francisco, CA",
      "specifications": ["Adventurous", "Loyal", "Good with people"],
      "briefDetail": "Coco is an adventurous Chihuahua who loves exploring new places and is very loyal.",
      "detailedDetails": "Coco is 3 years old, spayed, and enjoys outdoor adventures. She is very loyal and gets along well with people.",
      "imgUrl": "https://i.pinimg.com/564x/8f/6b/07/8f6b07039461f37d1117464370165880.jpg"
    },
    {
      "id": 18,
      "title": "Sweet Scottish Fold",
      "name": "Mittens",
      "breed": "Scottish Fold",
      "type": "Cat",
      "location": "Seattle, WA",
      "specifications": ["Sweet", "Affectionate", "Good with children"],
      "briefDetail": "Mittens is a sweet Scottish Fold who loves attention and is great with children.",
      "detailedDetails": "Mittens is 2 years old, neutered, and has a distinctive folded ear appearance. She is affectionate and enjoys being around people.",
      "imgUrl": "https://media.istockphoto.com/id/467801366/photo/lovable-scottish-fold-cat.jpg?s=612x612&w=0&k=20&c=0OAfVoF3NaPUGRJG9260elTgUykTxFbNOlDlEVNu_Hc="
    },
    {
      "id": 19,
      "title": "Friendly Poodle",
      "name": "Rex",
      "breed": "Poodle",
      "type": "Dog",
      "location": "Denver, CO",
      "specifications": ["Friendly", "Intelligent", "Low shedding"],
      "briefDetail": "Rex is a friendly Poodle who is intelligent and low shedding, making him a great companion.",
      "detailedDetails": "Rex is 4 years old and enjoys learning new tricks. He is friendly, intelligent, and has a low shedding coat.",
      "imgUrl": "https://c8.alamy.com/comp/2H0N1HE/the-nice-poodle-dog-isolated-on-white-2H0N1HE.jpg"
    },
    {
      "id": 20,
      "title": "Playful Ferret",
      "name": "Nibbles",
      "breed": "Ferret",
      "type": "Ferret",
      "location": "Austin, TX",
      "specifications": ["Playful", "Curious", "Social"],
      "briefDetail": "Nibbles is a playful Ferret who enjoys exploring and interacting with people.",
      "detailedDetails": "Nibbles is 1 year old and loves to play with toys and explore his surroundings. He is very social and enjoys being around people.",
      "imgUrl": "https://img.freepik.com/premium-photo/ferret-s-playful-pose-shines-bright-against-white-canvas_1008702-1793.jpg"
    },
    {
      "id": 21,
      "title": "Gentle Greyhound",
      "name": "Sasha",
      "breed": "Greyhound",
      "type": "Dog",
      "location": "San Diego, CA",
      "specifications": ["Gentle", "Calm", "Good with families"],
      "briefDetail": "Sasha is a gentle Greyhound who is calm and great with families.",
      "detailedDetails": "Sasha is 6 years old, spayed, and has a gentle demeanor. She is calm and enjoys lounging around the house.",
      "imgUrl": "https://img.freepik.com/premium-photo/photo-gentle-greyhound-with-its-graceful-posture-pristine-white-surface-generative-ai_630290-8451.jpg"
    },
    {
      "id": 22,
      "title": "Friendly French Bulldog",
      "name": "Bubbles",
      "breed": "French Bulldog",
      "type": "Dog",
      "location": "Los Angeles, CA",
      "specifications": ["Friendly", "Playful", "Low maintenance"],
      "briefDetail": "Bubbles is a friendly French Bulldog who is playful and low maintenance.",
      "detailedDetails": "Bubbles is 2 years old, neutered, and enjoys playing with toys. He is very friendly and easy to care for.",
      "imgUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTW6ZM4k1oqOinMOX7EktQVG44JhG0SBHdoIA&s"
    },
    {
      "id": 23,
      "title": "Charming Lovebird",
      "name": "Peppy",
      "breed": "Lovebird",
      "type": "Bird",
      "location": "Phoenix, AZ",
      "specifications": ["Charming", "Social", "Colorful"],
      "briefDetail": "Peppy is a charming Lovebird who loves to interact with people and is very colorful.",
      "detailedDetails": "Peppy is 1 year old and enjoys being the center of attention. He is very social and loves to interact with people.",
      "imgUrl": "https://www.shutterstock.com/image-photo/pair-lovebirds-perched-on-tree-600nw-2163693069.jpg"
    },
    {
      "id": 24,
      "title": "Sweet Yorkshire Terrier",
      "name": "Bella",
      "breed": "Yorkshire Terrier",
      "type": "Dog",
      "location": "San Francisco, CA",
      "specifications": ["Sweet", "Affectionate", "Good with people"],
      "briefDetail": "Bella is a sweet Yorkshire Terrier who is affectionate and gets along well with people.",
      "detailedDetails": "Bella is 3 years old, spayed, and has a long, silky coat. She is very affectionate and enjoys being around people.",
      "imgUrl": "https://www.aiscribbles.com/img/variant/large-preview/19044/?v=3b5965"
    },
    {
      "id": 25,
      "title": "Elegant Abyssinian",
      "name": "Simba",
      "breed": "Abyssinian",
      "type": "Cat",
      "location": "New York, NY",
      "specifications": ["Elegant", "Active", "Affectionate"],
      "briefDetail": "Simba is an elegant Abyssinian who is active and loves attention.",
      "detailedDetails": "Simba is 2 years old, neutered, and has a sleek, elegant appearance. He is very active and enjoys interactive play.",
      "imgUrl": "https://www.shutterstock.com/image-photo/abyssinian-abys-breed-domestic-short-600nw-2497952475.jpg"
    },
    {
      "id": 26,
      "title": "Mellow Pug",
      "name": "Louie",
      "breed": "Pug",
      "type": "Dog",
      "location": "Chicago, IL",
      "specifications": ["Mellow", "Friendly", "Good with children"],
      "briefDetail": "Louie is a mellow Pug who is friendly and great with children.",
      "detailedDetails": "Louie is 4 years old, neutered, and enjoys lounging around the house. He is very friendly and gets along well with children.",
      "imgUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ0eepAPYs7z7qg6Xagv69D0nAISPGd3_Nhkg&s"
    },
    {
      "id": 27,
      "title": "Caring Rottweiler",
      "name": "Duke",
      "breed": "Rottweiler",
      "type": "Dog",
      "location": "Dallas, TX",
      "specifications": ["Caring", "Loyal", "Protective"],
      "briefDetail": "Duke is a caring Rottweiler who is loyal and protective of his family.",
      "detailedDetails": "Duke is 5 years old, neutered, and has a strong protective instinct. He is very loyal and loves spending time with his family.",
      "imgUrl": "https://cdn.shopify.com/s/files/1/0565/8021/0861/files/Downloader_20_3.png?v=1687164383"
    },
    {
      "id": 28,
      "title": "Playful Pomeranian",
      "name": "Teddy",
      "breed": "Pomeranian",
      "type": "Dog",
      "location": "San Diego, CA",
      "specifications": ["Playful", "Energetic", "Affectionate"],
      "briefDetail": "Teddy is a playful Pomeranian who loves to play and is very affectionate.",
      "detailedDetails": "Teddy is 2 years old and enjoys playing with toys. He is very energetic and affectionate, making him a great companion.",
      "imgUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRJHzN97JmEsjw797lY2LmVdFgzJCbc12u32A&s"
    },
    {
      "id": 29,
      "title": "Gentle Golden Retriever",
      "name": "Max",
      "breed": "Golden Retriever",
      "type": "Dog",
      "location": "Seattle, WA",
      "specifications": ["Gentle", "Loyal", "Good with families"],
      "briefDetail": "Max is a gentle Golden Retriever who is loyal and great with families.",
      "detailedDetails": "Max is 4 years old and enjoys playing fetch. He is very gentle and loyal, making him a great family pet.",
      "imgUrl": "https://www.shutterstock.com/image-photo/gentle-golden-retriever-260nw-1114869932.jpg"
    },
    {
      "id": 30,
      "title": "Charming Conure",
      "name": "Sunny",
      "breed": "Conure",
      "type": "Bird",
      "location": "Orlando, FL",
      "specifications": ["Charming", "Playful", "Colorful"],
      "briefDetail": "Sunny is a charming Conure who is playful and colorful.",
      "detailedDetails": "Sunny is 2 years old and enjoys interacting with people. He is very colorful and playful, making him a delightful companion.",
      "imgUrl": "https://www.shutterstock.com/image-photo/beautiful-parrot-sun-conure-on-600nw-527721265.jpg"
    },
    {
      "id": 31,
      "title": "Gentle Australian Shepherd",
      "name": "Riley",
      "breed": "Australian Shepherd",
      "type": "Dog",
      "location": "Portland, OR",
      "specifications": ["Gentle", "Intelligent", "Active"],
      "briefDetail": "Riley is a gentle Australian Shepherd who is intelligent and active.",
      "detailedDetails": "Riley is 3 years old and enjoys outdoor activities. He is very intelligent and has a gentle demeanor.",
      "imgUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRXBMM4KDS0fOzi9INgfbQ2x5ZUkKsCj3UVDw&s"
    },
    {
      "id": 32,
      "title": "Playful Pug",
      "name": "Waffles",
      "breed": "Pug",
      "type": "Dog",
      "location": "Atlanta, GA",
      "specifications": ["Playful", "Friendly", "Good with children"],
      "briefDetail": "Waffles is a playful Pug who is friendly and good with children.",
      "detailedDetails": "Waffles is 1 year old and loves to play with kids. He is very friendly and enjoys being around people.",
      "imgUrl": "https://www.shutterstock.com/image-photo/indy-musician-guitarist-pug-dogfunny-260nw-688080844.jpg"
    },
    {
      "id": 33,
      "title": "Elegant Maine Coon",
      "name": "Jasper",
      "breed": "Maine Coon",
      "type": "Cat",
      "location": "Minneapolis, MN",
      "specifications": ["Elegant", "Affectionate", "Good with families"],
      "briefDetail": "Jasper is an elegant Maine Coon who is affectionate and great with families.",
      "detailedDetails": "Jasper is 5 years old and has a majestic appearance. He is very affectionate and enjoys being around children and other pets.",
      "imgUrl": "https://www.shutterstock.com/image-photo/maine-coon-on-orange-background-600nw-104008487.jpg"
    },
    {
      "id": 34,
      "title": "Gentle Shih Tzu",
      "name": "Chloe",
      "breed": "Shih Tzu",
      "type": "Dog",
      "location": "San Jose, CA",
      "specifications": ["Gentle", "Affectionate", "Good with people"],
      "briefDetail": "Chloe is a gentle Shih Tzu who is affectionate and gets along well with people.",
      "detailedDetails": "Chloe is 4 years old, spayed, and enjoys being pampered. She is very gentle and has a loving nature.",
      "imgUrl": "https://media.istockphoto.com/id/1329835502/photo/portrait-of-cute-joyful-shih-tzu-dog-sitting-on-floor-with-sticked-out-tongue-isolated-over.jpg?s=612x612&w=0&k=20&c=YAUdY-mIsdyS47lILdypOli8z6XeBznYLnMDJ6_R86A="
    },
    {
      "id": 35,
      "title": "Charming Parrot",
      "name": "Charlie",
      "breed": "African Grey Parrot",
      "type": "Bird",
      "location": "Philadelphia, PA",
      "specifications": ["Charming", "Vocal", "Intelligent"],
      "briefDetail": "Charlie is a charming African Grey Parrot who is vocal and intelligent.",
      "detailedDetails": "Charlie is 8 years old and enjoys mimicking sounds and talking. He is very intelligent and loves interaction.",
      "imgUrl": "https://cdn.pixabay.com/photo/2019/12/30/05/22/bird-4728857_1280.jpg"
    },
    {
      "id": 36,
      "title": "Playful Cocker Spaniel",
      "name": "Lucy",
      "breed": "Cocker Spaniel",
      "type": "Dog",
      "location": "Baltimore, MD",
      "specifications": ["Playful", "Affectionate", "Good with families"],
      "briefDetail": "Lucy is a playful Cocker Spaniel who is affectionate and great with families.",
      "detailedDetails": "Lucy is 2 years old and enjoys playing with children. She is very affectionate and gets along well with other pets.",
      "imgUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3OZ9rM2W1jGuLZw_HqHNhnmvij2vVmxYFHA&s"
    },
    {
      "id": 37,
      "title": "Gentle Siberian Husky",
      "name": "Koda",
      "breed": "Siberian Husky",
      "type": "Dog",
      "location": "Salt Lake City, UT",
      "specifications": ["Gentle", "Energetic", "Loyal"],
      "briefDetail": "Koda is a gentle Siberian Husky who is energetic and loyal.",
      "detailedDetails": "Koda is 4 years old and enjoys running and outdoor activities. He is very loyal and has a gentle demeanor.",
      "imgUrl": "https://cdn.britannica.com/84/232784-050-1769B477/Siberian-Husky-dog.jpg"
    },
    {
      "id": 38,
      "title": "Sweet Bichon Frise",
      "name": "Misty",
      "breed": "Bichon Frise",
      "type": "Dog",
      "location": "Louisville, KY",
      "specifications": ["Sweet", "Playful", "Good with families"],
      "briefDetail": "Misty is a sweet Bichon Frise who is playful and great with families.",
      "detailedDetails": "Misty is 3 years old and enjoys playing with kids. She is very sweet and gets along well with other pets.",
      "imgUrl": "https://media.istockphoto.com/id/635988430/photo/cute-little-bichon-frise-dog.jpg?s=612x612&w=0&k=20&c=x__vTW3ocgOzNGjxvD1Z_MqNq2jhQ09HOL4SVnvAkZw="
    },
    {
      "id": 39,
      "title": "Friendly Pug",
      "name": "Peanut",
      "breed": "Pug",
      "type": "Dog",
      "location": "Nashville, TN",
      "specifications": ["Friendly", "Playful", "Good with children"],
      "briefDetail": "Peanut is a friendly Pug who is playful and good with children.",
      "detailedDetails": "Peanut is 1 year old and loves to play with kids. He is very friendly and enjoys being around people.",
      "imgUrl": "https://media.istockphoto.com/id/454238885/photo/pug-puppy-dog.jpg?s=612x612&w=0&k=20&c=Da9JqQ3ViGeNvM6IPGBprXBt8PLSQ8_rPgvYWhEtpHU="
    },
    {
      "id": 40,
      "title": "Elegant Turkish Angora",
      "name": "Luna",
      "breed": "Turkish Angora",
      "type": "Cat",
      "location": "Baltimore, MD",
      "specifications": ["Elegant", "Affectionate", "Playful"],
      "briefDetail": "Luna is an elegant Turkish Angora who is affectionate and playful.",
      "detailedDetails": "Luna is 2 years old and has a beautiful, flowing coat. She is very affectionate and enjoys interactive play.",
      "imgUrl": "https://img.freepik.com/premium-photo/elegant-turkish-angora-kitten-walking-light-blue_351987-1875.jpg"
    }
  ]
  const type=new Set();
  filterData.map((item)=>{
    type.add(item.type);
})
//  export const set = type.forEach(element => {return element });
  
export const set=Array.from(type);
  
  console.log(set);